import qz from "qz-tray";
import { Factura } from "../types/configuration";

// Extender la definición de tipos de qz-tray
declare module "qz-tray" {
  interface QZ {
    configs: {
      create(
        printer: string,
        options?: { copies?: number }
      ): {
        printer: string;
        copies: number;
      };
    };
    print(
      config: { printer: string; copies: number },
      data: string[]
    ): Promise<any>;
    websocket: {
      connect(): Promise<any>;
      disconnect(): Promise<any>;
      isActive(): boolean;
    };
    printers: {
      getDefault(): Promise<string>;
    };
  }
}

// Configuración de la impresora
const printerConfig = {
  printer: "", // Se establecerá dinámicamente
  copies: 1,
  jobName: "Factura",
};

// Obtener la impresora por defecto
const getDefaultPrinter = async () => {
  try {
    const defaultPrinter = await (qz as any).printers.getDefault();
    printerConfig.printer = defaultPrinter;
    return defaultPrinter;
  } catch (error) {
    console.error("Error al obtener la impresora por defecto:", error);
    throw error;
  }
};

// Inicializar qz-tray
export const initializeQz = async () => {
  try {
    // Asegurarse de que qz-tray está cargado
    if (!qz) {
      throw new Error("qz-tray no está cargado correctamente");
    }

    // Verificar si ya hay una conexión activa
    if ((qz as any).websocket.isActive()) {
      console.log("Ya existe una conexión activa con qz-tray");
      return true;
    }

    // Intentar establecer la conexión
    console.log("Intentando conectar con qz-tray...");

    // Intentar conectar con un timeout
    const connectionPromise = (qz as any).websocket.connect();
    const timeoutPromise = new Promise((_, reject) => {
      setTimeout(
        () => reject(new Error("Timeout al conectar con QZ Tray")),
        5000
      );
    });

    await Promise.race([connectionPromise, timeoutPromise]);
    console.log("Conexión establecida con qz-tray");
    await getDefaultPrinter();

    return true;
  } catch (error) {
    console.error("Error al inicializar qz-tray:", error);
    if (error instanceof Error) {
      if (error.message.includes("Unable to establish connection")) {
        console.error("Por favor, asegúrate de que:");
        console.error(
          "1. QZ Tray está instalado y ejecutándose en tu computadora"
        );
        console.error(
          "2. La aplicación web está accediendo desde http://localhost o https://"
        );
        console.error(
          "3. QZ Tray tiene permisos para conectarse a esta aplicación"
        );
      }
    }
    throw error;
  }
};

const now = new Date();
const fecha = now.toLocaleDateString("es-AR", {
  day: "2-digit",
  month: "2-digit",
  year: "numeric",
});
const hora = now.toLocaleTimeString("es-AR", {
  hour: "2-digit",
  minute: "2-digit",
  second: "2-digit",
  hour12: false,
});

// Formatear el contenido del ticket
const formatTicketContent = (factura: Factura) => {
  const lines = [];

  // Encabezado
  lines.push(`MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKO0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;,;oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c''',:xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0c''''',:dOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKOO0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,''''''',:okKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXK0kxdddxxkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXo,''''''''',;cdk0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXK00OxdooooooddkOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNXXXKKKK00OOOOOkkkkkkkkkkkkkkkkOOOOOO00KKXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc,'''''''''''',:ldk0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNXXK0OkxdollccccclodkOKKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXKK00OkkkxxdddoooooooooooooooooooooooooooooooooooooooddxxkO0KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKXWMMMMMMMMMMMMMMMMWKxc,''''''''''''''',;:loxkO0KKXXNNNNNWWWWWMMMMMMWWWWWWWNNNNNXXKK00Okxxdollc:;;;;::cloxkO0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXK0OOkxxddooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooodxkO0KXNWWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkod0NWMMMMMMMMMMMMMMMMWN0xoc;,''''''''''''''''',,;;;::cccllooddddddddddooollcccc:::;;;,,,,;:clodxkkOKXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXK00OkxxddoooooooooooooooooooooooooooooooddddddddddddddddddddoooooooooooooooooooooooooodxkOKXNWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dood0NMMMMMMMMMMMMMMMMMMMMWXKOkdoc:;,,'''''''''''''''''''''''''''''''''''',,,;::cllodxkkO0KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXK0OOkxxddooooooooooooooooooooooooddxxkkOOO000KKKKXXXXNNNNNNNNNNNNXXXXXKKK00OOkkxddoooooooooooooooooodxOKNWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dooodONWMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Okxxdoollcc:::;;;;;;;;::::ccllooddxxkO00KXXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXKK0OkxxdoooooooooooooooooooooodddxkkOO00KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXK00OkxdooooooooooooooodkKNWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkoooooxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNXXXXXKKKXXXXXXNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXK0OOkxddooooooooooooooooooooddxxkOO0KKXXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0OkdoooooooooooooxOXWMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxooooodkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNXXK0OkkxddoooooooooooooooooooddxkOO0KXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0OxdoooooooooodkKNWMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdoooooox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXK0OkkkxddooooooooooooooooooooddxkO00KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0kxdooooooodk0NWMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxooooooodk0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXK0OOkxxddooooooooooooooooooooooddxkO00KXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOkdoooooox0XWMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xoooooooodkOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNXKK0OkkxxdoooooooooooooooooooooooodxxkO0KKXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOkdooood0NW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kdooooooooodxk0KXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNXXKK00OOkkxxddoooooooooooooooooooooooddxxkkO0KKXNWWMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Oxood0W
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxoooooooooooodxxkO00KXXNNNNWWWWWWWWWWWWWWWWWWWWWWNNNNNXXXKK00OOkkxxddoooooooooooooooooooooooooooodxxkOO0KXNNNWWMMMMMMMMMMMMWNX0Oxdod0WMMMMMMMMMMMMMMWWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKO0NW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kdooooooooooooooooodddxxxkkkkkkkkkkkkkkkkkkkkxxxxddddooooooooooooooooooooooooooooooodddxkkO0KXXNWWMMMMMMMMMMMMMMMMMMNKOxoc:,,''''lKWMMMMMMMMMWN0kdllclodkKWMMMMMMMMMMMMWNXXNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOkdooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooddxxkkO00KXXNWWWWNNXKNWMMMMMMMMMMMMMMMMWKkl:,'''''''''',dXMMMMMMMMNOl;'''''''',;oKWMMMMMMMMMMXd:::clodddxkO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0OkxdooooooooooooooooooooooooooooooooooooooooooooooooooodxxxkOO00KKXNNWWWMMMMMWNKOxdlc:;lKWMMMMMMMMMMMMMWKd:,'''''''''''''';kNMMMMMMNx;'''''''''''''lKWMMMMMMMMWKl''''''''''',,oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKK0OkkxxddoooooooooooooooooooooooodddddxxkkkOO00KKXXNNWWMMMMMMMMMMMMMMWKOdc;,'''''',oXWMMMMMMMMMMMNk:,''''''''''''''''':OWMMMMWKl'''''''''''''';xWMMMMMMMMMKl'''''''''''',oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXXKKKK00000000000000KKKXXXXNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMWNOo:,''''''''''';dNMMMMMMMMMMNk;'''''''''''''''',;co0WMMMMMXo,''''''''''''':OWMMMMMMMMMXo'''''''''''',dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl;''''''''''''''';xNMMMMMMMMWKl'''''''''''''';ok0KNWMMMMMMMW0l,'''''''''',:xNMMMMMMMMMMXo,''''''''''';xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;''''''''''''''''',c0WMMMMMMMWO:''''''''''''';kNWMMMMMMMMMMMMWXOoc:;,,;:coxKWMMMMMMMMMMMNo,''''''''''';kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;'''''''''''''',:ldk0NMMMMMMMMWO:'''''''''''''lKWMMMMMMMMMMMMMMMMWNXK0KKXNWWMMMMMMMMMMMMMXd,''''''''''',dKNNNNXXXXXNWMMMMMMMMMMMMMMMMWWNXKK0000KKXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl''''''''''''',lOXWWMMMMMMMMMMMW0c'''''''''''''c0WMMMMMMMMMMMMMWNXXXXKKXXK0OkkxkXMMMMMWX0Oxc,'''''''''''',::::::::::xNMMMMMMMMMMMMWN0kdlc:;,,,,,;;::codk0XWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:''''''''''''':OWMMMMMMMMMMMMMMMXo,'''''''''''';xXNXXK0OOKWMMMMKo;;;;;;;;;,,''':OWMMMMKl,,,'''''''''''''''''''''''',dNMMMMMMMMMWN0dc;''''''''''''''''''',:okKWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkxdollcccllodxkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c''''''''''''':OWMMMMMMMMMMMMMMMWk;''''''''''''';cc:;;,,,oXMMMMXo,''''''''''''';OWMMMWKc''''''''''''''''''''''''''';xNMMMMMMMMXOl;''''''''''''''''''''''''',;o0NMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xoc;,''''''''''''''',,;coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,'''''''''''';xNWMMWWNNNWMMMWX0Oo;''''''''''''''''''''''c0WMMMWk;''''''''''''';OWMMMMXl,'''''''''''''''''''''''''',xNMMMMMMW0o;'''''''''''''''''''''''''''''';oKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWN0dc,'''''''''''''''''''''''''',;lxKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;'''''''''''''ckOkxdolcdKMMMKl,''''''''''''''''''''''''';xWMMMMKc''''''''''''';kWMMMMXl''''''''''''''''''''''''''',dNMMMMMNk:''''''''''''''''''''''''''''''''',cOWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXkl;'''''''''''''''''''''''''''''''',;lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl,''''''''''''',,,''''';kWMWKc'''''''''''''''''''''''''',oXMMMMNd,'''''''''''';kWMMMMKl,'''''''''''''''''',,,,,,,,;xNMMMMNk:''''''''''''''',;;;;,''''''''''''''':kNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWXxc,''''''''''''''''''''''''''''''''''''',ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kc,''''''''''''''''''''',oXWWXd,''''''''''''''''''''''''''c0WMMMWk;'''''''''''';xNMMMMWKOkko;'''''''''''':dOOOOOOOO0XWMMMWOc''''''''''''';cxO0KKKOxl;'''''''''''''c0WMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNOl,''''''''''''''''''''''''''''''''''''''''',lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNNNNNWWMMMMWOc,,'''''''''''''''''''''''':ONWWk;'''''''''''''''''''''''',,cOWMMMW0c'''''''''''',dNMMMMMMMMW0c''''''''''''lKWMMMMMMMMMMMMMXo,''''''''''',cONWMMMMMMWNOc,''''''''''',dXMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMXx;''''''''''''''''''''''''''''''''''''''''''',lKWMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMW0dolllcccccclOWMMMWO:'''''''''''''''''''''''''',o0XWKl'''''''''''''''''',cdxxkO0KNMMMMMKl'''''''''''',oXMMMMMMMMMKc''''''''''''cKMMMMMMMMMMMMMM0:''''''''''',l0WMMMMMMMMMMW0c,'''''''''''c0WMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWKo,'''''''''''''''''',:cloooolc:,''''''''''''';oKWMMMMMMMMMMMMMMMWNX0Oxdooddxk0XWXo,'''''''''',oXMMMMXl,'''''''''''''''''''''''''':o0WNk::c:;,'''''''''''',dNWMMMMMMMMMMMXo,''''''''''''lKMMMMMMMMM0c''''''''''''cKMMMMMMMMMMMMMWk;''''''''''';kWMMMMMMMMMMMMNx;''''''''''';OWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWKo,'''''''''''''''';lx0XNWWWWWWNX0xo:,'''''''':kNWMMMMMMMMMMMMWN0koc;,'''''''',;:oo:''''''''''''lKMMMMWk;''''''''''''''''''',;:clodkOXWMNXXNXk:'''''''''''''lKMMMMMMMMMMMMNx;'''''''''''':0WMMMMMMMM0c''''''''''''c0WMMMMMMMMMMMMNx;''''''''''':OWMMMMMMMMMMMMNk;''''''''''';OWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMXd,''''''''''''''';o0NWMMMMMMMMMMMMMWKkl;'''',l0WMMMMMMMMMMMMWKxc;,''''''''''''''''''''''''''''''c0WMMMMKl,''''''''''''''''',o0XNWWWMMMMMMMMMMKl''''''''''''':OWMMMMMMMMMMMWk;'''''''''''';kWMMMMMMMM0c'''''''''''';kNMMMMMMMMMMMMWk;''''''''''',xNMMMMMMMMMMMWKo,'''''''''''c0WMMMMMMMMMMM
MMMMMMMMMMMMMMMMWO:'''''''''''''',cONMMMMMMMMMMMMMMMMMMWNOl;,:xXWMMMMMMMMMMMWKd:,''''''''''''''''''''''''''''''''';kWMMMMWkc:cc:,'''''''''''''lKWMMMMMMMMMMMMMMNd,'''''''''''',dNMMMMMMMMMMMW0:'''''''''''',xNMMMMMMMW0:'''''''''''''cOXWWWWWNXKXNMW0c'''''''''''';xXWMMMMMMMMWKd,''''''''''',oXMMMMMMMMMMMM
MMMMMMMMMMMMMMMMKl,''''''''''''',c0WMMMMMMMMMMMMMMMMMMMMMWN0kKWMMMMMMMMMMMMNkc,''''''''''''''''''''''''''''''''''',oXMMMMMWXXNN0l''''''''''''';kWMMMMMMMMMMMMMMWO;'''''''''''''lKWMMMMMMMMMMWKl'''''''''''',oXMMMMMMMW0:'''''''''''''';clooolc:;c0WMNd;'''''''''''',lkKNWWWWNKxc,'''''''''''':OWMMMMMMMMMMMM
MMMMMMMMMMMMMMMWk;'''''''''''''':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;'''''''''''''''',,;;;,''''''''''''''''c0WMMMMMMMMMNx;'''''''''''',lXMMMMMMMMMMMMMMWKc''''''''''''';kWMMMMMMMMMMMXo'''''''''''''lKMMMMMMMW0:''''''''''''''''''''''''c0MMWKo,''''''''''''',;cloolc;,''''''''''''';xNMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNd,''''''''''''',oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:''''''''''''',:oxO0KKKOxo:,'''''''''''';xNMMMMMMMMMW0c''''''''''''':OWMMMMMMMMMMMMMMXo,'''''''''''',oXMMMMMMMMMMMXo,'''''''''''':0WMMMMMMM0c''''''''''''''''''''''''cKWMMWKo,'''''''''''''''''''''''''''''''''';xNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMXo,''''''''''''';kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl'''''''''''',:xKWMMMMMMMMWKd;''''''''''''lKMMMMMMMMMMNd,'''''''''''',oXMMMMMMMMMMMMMMWk;''''''''''''':OWMMMMMMMMMMNd,'''''''''''';kWMMMMMMMXo,'''''''''''''''''''''''cKMMMMMXx:,''''''''''''''''''''''''''''''':kNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMXo'''''''''''''';kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:''''''''''''cOWMMMMMMMMMMMMNx;''''''''''';kWMMMMMMMMMWO:''''''''''''':OWMMMMMMMMMMMMMW0c''''''''''''',dNMMMMMMMMMMWk;'''''''''''',xNMMMMMMMWKl,'''''''''''''''''''',:xNMMMMMMWKd:,''''''''''''''''''''''''''';dKWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMXo,''''''''''''';kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,''''''''''',dNMMMMMMMMMMMMMWKl,'''''''''''lKMMMMMMMMMMKl''''''''''''',oXMMMMMMMMMMMMMMXo,'''''''''''''cKWMMMMMMMMMWO:'''''''''''',oXMMMMMMMMWXkl:,''''''''''',,;:ldOXWMMMMMMMMMWKkl:,''''''''''''''''''''',cdKWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNd,''''''''''''',oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,''''''''''',dNMMMMMMMMMMMMMMXo,''''''''''';xNMMMMMMMMMNx;''''''''''''';kWMMMMMMMMMMMMMNx;''''''''''''';kWMMMMMMMMMM0:'''',,,,;;::lxNMMMMMMMMMMWNXOkxdoooooddxkOKXWWMMMMMMMMMMMMMMWWKOdlc;,,'''''''''',;:lx0XWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWk;'''''''''''''';kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;''''''''''''lKWMMMMMMMMMMMMW0c'''''''''''''c0WMMMMMMMMW0c''''''''''''',lKMMMMMMMMMMMMMWO:''''''''''''',dNMMMMMMMMMMN0kkkkOO00KKXNNWMMMMMMMMMMMMMMMMMMWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0OkxxddddxxkOKXWWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMKl''''''''''''''':kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0c'''''''''''',l0WMMMMMMMMMMN0c,''''''''''''',oXMMMMMMMMMNd,''''''''''''';kWMMMMMMMMMMMMWXo,,,;;:cllodxxOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWk;''''''''''''''';dKWMMMMMMMMMMMMMMMMMWKkkKWMMMMMMMMMMMMNd,'''''''''''',;oOKNWWWNNKko;'''''''''''''''';kWMMMMMMMMWO:''''''''''''''oXMMMMMMMMMMMMMWX000KXXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMXd;''''''''''''''',:oOXWWMMMMMMMMWWX0ko:,,c0WMMMMMMMMMMMWKl,'''''''''''''',;clollc;,'''''''''''''''''',lKMMMMMMMMMXl''''''''',;::lxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWXd;''''''''''''''''',:ldkOOOOOkxdl:;,'''''cOWMMMMMMMMMMMW0c,'''''''''''''''''''''''''''''''''''''''''';xNMMMMMMMMWOc::clodxkO0XNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWXx;''''''''''''''''''''',,,,,'''''''''''''cONMMMMMMMMMMMW0l,'''''''''''''''''''''''''',,,'''''''''''',lKMMMMMMMMMWNXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNOc,'''''''''''''''''''''''''''''''''''''':ONMMMMMMMMMMMWXx:'''''''''''''''''''''''';oOx;'''''',,;cldONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWKd:'''''''''''''''''''''''''''''''''''''':OWMMMMMMMMMMMMWKd:,''''''''''''''''''',ckNMNxc:lodxO0KNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWNNNNNXXXXXXXKKKKKKKKKKXXXNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMW0d:,'''''''''''''''''''''''''''''''''';oKWMMMMMMMMMMMMMMWXko:,''''''''''''',;lkXWMMMWXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNXXXKK00OOOkkkkxxxxdddddoooooooooooooooddddxkkkO00KKXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWWWMMMMMMMMMMWKkl;,'''''''''''''''''''''''''''',:d0NMMMMMMMMMMMMMMMMMMMWXOxolc::;;::cldkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXK0OOkkxxdddoooooooooooooooooooooooooooooooooooooooooooooooooddxkkO0KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWKkkKWMMMMMMMMMMMNKkoc;,'''''''''''''''''''',;cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXKKXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXK0OOkxxddoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooodxkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWKxooxKWMMMMMMMMMMMMMWNKOkdlc:;;;;,,,,;;::coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXK00OkkxddoooooooooooooooooooooooooooddddxxxkkkkkOOOOOOOOOOOOOOkkkkkkxxdddooooooooooooooooooooodxk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMW0doooxKWMMMMMMMMMMMMMMMMMWWNXXKK00000KKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNXK0OkkxddooooooooooooooooooooooooddxxkOOO00KKXXXNNWWWWWWWWMMMMMMMMMMMMMWWWWWWWNNXXK00OOkxddoooooooooooooooooxk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWKxoooox0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXKK0OkkkxdoooooooooooooooooooooodxxkkOO0KKXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0OkxdoooooooooooooodkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMW0doooookKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXK00OkxddoooooooooooooooooooooddxkOO00KXXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOkxdooooooooooodx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMN0xooooodx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXKK0OkkxddooooooooooooooooooooddxkkO0KKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNNXXXXXXXXXNNNNWWWWMMMMMMMMMMMMMMMMMMMMMWNXKOkxooooooooooxOXWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWXOdooooooxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXKK0OkkxddoooooooooooooooooooooddxxkO0KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0OkxxddolllcccccccccccloodddxkOO0KXXNWMMMMMMMMMMMMMMMMWNX0OkdooooooodOXWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWKkdoooooodxOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXK0OOkxxddoooooooooooooooooooooddxkkO0KXXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkkxxddxxkkkkkkkkkkxdoolc:;;;;;;;;;;;;::cldkOKNWMMMMMMMMMMMMMMMWWNK0kdooooodkKWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNKkooooooooodkOKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNXKK0OOkxxddoooooooooooooooooooooooddxkOO0KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNWWWWWMMMMMMMMMMMMWWWWNXKOkxol:;;;;;;;;;;;;;:ldxOKNWMMMMMMMMMMMMMMMWNK0kdoood0WMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWNKkdoooooooooodxkkO0KXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNXXKK00OOkkxxxddooooooooooooooooooooooooddxkkO00KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKOkdoc:;;;;;;;;;;;;:ldk0XNWMMMMMMMMMMMMMMWX0kxdONMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWX0kdoooooooooooooooddxkkOO00KKXXXXXXXXXXXXXXXXKKKKK0000OOkkkxxdddooooooooooooooooooooooooooooddxkkO00KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxol:;;;;;;;;;;;:coxOKNWMMMMMMMMMMMMMWNXNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXKOxdooooooooooooooooooooooooodddddddddoooooooooooooooooooooooooooooooooooooooooddxxkkO00KXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxoc:;;;;;;;;;;;cokKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOkxdooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooddxxkkO00KXXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0kdl:;;;;;;;;;;cdONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXK0OkxddoooooooooooooooooooooooooooooooooooooooodddxxkkOO00KKXXNWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOdl:;;;;;;;;:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXK00OOOkkkxxxxxxxxxxxxxxxxkkkkOOOO000KKKXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkoc;;;;;;;ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNNNNNNNNNNNNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKkl:;;;;;:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0dc;;;;l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxdx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`);
  lines.push("-------------------");
  lines.push("Dirección: Lavalle 773");
  lines.push("Tel: (3408) 680521");
  lines.push("CUIT: 20-18096191-8");
  lines.push("-------------------");
  lines.push(`Fecha: ${fecha}`);
  lines.push(`Hora: ${hora}`);
  lines.push(`Ticket #: ${factura.id || "N/A"}`);
  lines.push(`Cliente: ${factura.clienteId || "Consumidor Final"}`);
  lines.push("-------------------");

  // Detalles de la factura
  if (factura.facturaRenglons && factura.facturaRenglons.length > 0) {
    lines.push("PRODUCTOS");
    lines.push("-------------------");
    factura.facturaRenglons.forEach((renglon) => {
      lines.push(`${renglon.detalle || ""}`);
      lines.push(
        `${renglon.cantidad || 0} x $${
          renglon.precioVenta?.toFixed(2) || 0
        } = $${((renglon.cantidad || 0) * (renglon.precioVenta || 0)).toFixed(
          2
        )}`
      );
    });
  }

  // Totales
  lines.push("-------------------");
  lines.push(`Subtotal: $${factura.subtotal?.toFixed(2) || "0.00"}`);
  if (factura.descuento > 0) {
    lines.push(`Descuento: -$${factura.descuento.toFixed(2)}`);
  }
  if (factura.interes > 0) {
    lines.push(`Interés: +$${factura.interes.toFixed(2)}`);
  }
  lines.push(`Total: $${factura.total?.toFixed(2) || "0.00"}`);

  // Pagos
  lines.push("-------------------");
  lines.push("PAGOS");
  if (factura.pagos && factura.pagos.length > 0) {
    factura.pagos.forEach((pago) => {
      lines.push(
        `${pago.tipoPagoNombre?.trim() || ""}: $${
          pago.monto?.toFixed(2) || "0.00"
        }`
      );
    });
  }

  // Pie
  lines.push("-------------------");
  lines.push("¡Gracias por su compra!");
  lines.push("-------------------");
  lines.push(""); // Línea en blanco al final para cortar el ticket

  return lines.join("\n");
};

// Servicio de impresión
export const printService = {
  printInvoice: async (factura: Factura) => {
    try {
      // Verificar si qz-tray está cargado
      if (!qz) {
        throw new Error("qz-tray no está cargado correctamente");
      }

      // Solo conectar si no hay una conexión activa
      if (!(qz as any).websocket.isActive()) {
        console.log("Intentando conectar con qz-tray...");
        await initializeQz();
      }

      // Formatear el contenido del ticket
      const ticketContent = formatTicketContent(factura);

      // Configurar el trabajo de impresión usando qz.configs.create
      const config = (qz as any).configs.create(printerConfig.printer, {
        copies: printerConfig.copies,
      });

      console.log("Datos a imprimir:", {
        config,
        ticketContent,
        factura,
      });

      // Enviar a imprimir usando qz.print con el contenido del ticket directamente
      await (qz as any)
        .print(config, [ticketContent])
        .then(() => {
          console.log("Impreso OK");
        })
        .catch((error: any) => console.error(error));

      return true;
    } catch (error) {
      console.error("Error al imprimir la factura:", error);
      throw error;
    }
  },

  // Cerrar la conexión con qz-tray
  closeConnection: async () => {
    try {
      if ((qz as any).websocket.isActive()) {
        await (qz as any).websocket.disconnect();
      }
    } catch (error) {
      console.error("Error al cerrar la conexión con qz-tray:", error);
      throw error;
    }
  },
};
